// Language translations
const translations = {
    uz: {
        nav_home: 'Bosh sahifa',
        nav_rooms: 'Xonalar',
        nav_amenities: 'Qulayliklar',
        nav_reviews: 'Sharhlar',
        nav_contact: 'Aloqa',
        hero_title: "Marjon Hotel'ga xush kelibsiz",
        hero_subtitle: 'Premium darajadagi xizmat va unutilmas dam olish',
        hero_btn: 'Bron qilish',
        stats_guests: 'Mamnun mijozlar',
        stats_rooms: 'Hashamatli xonalar',
        stats_awards: 'Mukofotlar',
        stats_years: 'Yillik tajriba',
        why_title: 'Nega bizni tanlashadi?',
        why_safety: '100% Xavfsizlik',
        why_safety_desc: '24/7 qo\'riqlash tizimi va videokuzatuv',
        why_wifi: 'Bepul Wi-Fi',
        why_wifi_desc: 'Yaqin masofadagi yuqori tezlikdagi internet',
        why_service: 'Premium xizmat',
        why_service_desc: '24/7 xona xizmati va konsyerj',
        why_location: 'Qulay joylashuv',
        why_location_desc: 'Shahar markazida, barcha diqqatga sazovor joylar yaqinida',
        rooms_title: 'Xonalar paketi',
        room_standard: 'Standart xona',
        room_vip: 'VIP xona',
        room_premium: 'Premium xona',
        room_wifi: 'Bepul Wi-Fi',
        room_tv: 'Televizor',
        room_ac: 'Konditsioner',
        room_minibar: 'Mini-bar',
        room_view: 'Shahar manzarasi',
        room_jacuzzi: 'Jakuzi',
        room_breakfast: 'Nonushta kiritilgan',
        room_per_night: '/ kecha',
        room_book: 'Bron qilish',
        amenities_title: 'Mehmonxonadagi qulayliklar',
        am_pool: 'Basseyn',
        am_spa: 'Spa markazi',
        am_gym: 'Fitnes zal',
        am_restaurant: 'Restoran',
        am_parking: 'Bepul parking',
        am_kids: 'Bolalar maydonchasi',
        staff_title: 'Bizning jamoa',
        staff_manager: 'Bosh menejer',
        staff_reception: 'Administrator',
        staff_chef: 'Bosh oshpaz',
        reviews_title: 'Mijozlar sharhlari',
        map_title: 'Bizning manzil',
        booking_title: 'Buyurtma berish',
        form_name: 'Ism Familiya',
        form_phone: 'Telefon raqam',
        form_room: 'Xona turi',
        form_checkin: 'Kelish sanasi',
        form_checkout: 'Ketish sanasi',
        form_comment: 'Izoh',
        form_submit: 'Buyurtma berish',
        footer_desc: 'Premium darajadagi mehmonxona - sizning ikkinchi uyingiz',
        footer_contact: 'Aloqa',
        footer_social: 'Ijtimoiy tarmoqlar',
        footer_rights: 'Barcha huquqlar himoyalangan.'
    },
    ru: {
        nav_home: 'Главная',
        nav_rooms: 'Номера',
        nav_amenities: 'Удобства',
        nav_reviews: 'Отзывы',
        nav_contact: 'Контакты',
        hero_title: 'Добро пожаловать в Marjon Hotel',
        hero_subtitle: 'Премиум сервис и незабываемый отдых',
        hero_btn: 'Забронировать',
        stats_guests: 'Довольных гостей',
        stats_rooms: 'Роскошных номеров',
        stats_awards: 'Наград',
        stats_years: 'Лет опыта',
        why_title: 'Почему выбирают нас?',
        why_safety: '100% Безопасность',
        why_safety_desc: 'Круглосуточная охрана и видеонаблюдение',
        why_wifi: 'Бесплатный Wi-Fi',
        why_wifi_desc: 'Высокоскоростной интернет',
        why_service: 'Премиум сервис',
        why_service_desc: 'Обслуживание номеров 24/7',
        why_location: 'Удобное расположение',
        why_location_desc: 'В центре города, рядом с достопримечательностями',
        rooms_title: 'Пакеты номеров',
        room_standard: 'Стандартный номер',
        room_vip: 'VIP номер',
        room_premium: 'Премиум номер',
        room_wifi: 'Бесплатный Wi-Fi',
        room_tv: 'Телевизор',
        room_ac: 'Кондиционер',
        room_minibar: 'Мини-бар',
        room_view: 'Вид на город',
        room_jacuzzi: 'Джакузи',
        room_breakfast: 'Завтрак включен',
        room_per_night: '/ ночь',
        room_book: 'Забронировать',
        amenities_title: 'Удобства отеля',
        am_pool: 'Бассейн',
        am_spa: 'Спа-центр',
        am_gym: 'Фитнес-зал',
        am_restaurant: 'Ресторан',
        am_parking: 'Бесплатная парковка',
        am_kids: 'Детская площадка',
        staff_title: 'Наша команда',
        staff_manager: 'Главный менеджер',
        staff_reception: 'Администратор',
        staff_chef: 'Шеф-повар',
        reviews_title: 'Отзывы клиентов',
        map_title: 'Наш адрес',
        booking_title: 'Оформление заказа',
        form_name: 'Имя Фамилия',
        form_phone: 'Номер телефона',
        form_room: 'Тип номера',
        form_checkin: 'Дата заезда',
        form_checkout: 'Дата выезда',
        form_comment: 'Комментарий',
        form_submit: 'Забронировать',
        footer_desc: 'Премиум отель - ваш второй дом',
        footer_contact: 'Контакты',
        footer_social: 'Социальные сети',
        footer_rights: 'Все права защищены.'
    },
    en: {
        nav_home: 'Home',
        nav_rooms: 'Rooms',
        nav_amenities: 'Amenities',
        nav_reviews: 'Reviews',
        nav_contact: 'Contact',
        hero_title: 'Welcome to Marjon Hotel',
        hero_subtitle: 'Premium service and unforgettable relaxation',
        hero_btn: 'Book Now',
        stats_guests: 'Happy Guests',
        stats_rooms: 'Luxury Rooms',
        stats_awards: 'Awards',
        stats_years: 'Years Experience',
        why_title: 'Why Choose Us?',
        why_safety: '100% Security',
        why_safety_desc: '24/7 security system and CCTV',
        why_wifi: 'Free Wi-Fi',
        why_wifi_desc: 'High-speed internet access',
        why_service: 'Premium Service',
        why_service_desc: '24/7 room service and concierge',
        why_location: 'Convenient Location',
        why_location_desc: 'City center, near all attractions',
        rooms_title: 'Room Packages',
        room_standard: 'Standard Room',
        room_vip: 'VIP Room',
        room_premium: 'Premium Room',
        room_wifi: 'Free Wi-Fi',
        room_tv: 'TV',
        room_ac: 'Air Conditioning',
        room_minibar: 'Mini-bar',
        room_view: 'City View',
        room_jacuzzi: 'Jacuzzi',
        room_breakfast: 'Breakfast Included',
        room_per_night: '/ night',
        room_book: 'Book Now',
        amenities_title: 'Hotel Amenities',
        am_pool: 'Swimming Pool',
        am_spa: 'Spa Center',
        am_gym: 'Fitness Center',
        am_restaurant: 'Restaurant',
        am_parking: 'Free Parking',
        am_kids: 'Kids Playground',
        staff_title: 'Our Team',
        staff_manager: 'General Manager',
        staff_reception: 'Receptionist',
        staff_chef: 'Head Chef',
        reviews_title: 'Guest Reviews',
        map_title: 'Our Location',
        booking_title: 'Make a Reservation',
        form_name: 'Full Name',
        form_phone: 'Phone Number',
        form_room: 'Room Type',
        form_checkin: 'Check-in Date',
        form_checkout: 'Check-out Date',
        form_comment: 'Comment',
        form_submit: 'Submit Booking',
        footer_desc: 'Premium hotel - your second home',
        footer_contact: 'Contact',
        footer_social: 'Social Media',
        footer_rights: 'All rights reserved.'
    }
};
